package com.plcoding.bookpedia.book.data.database

import androidx.room.RoomDatabaseConstructor

// This constructor is unique to KMP
@Suppress("NO_ACTUAL_FOR_EXPECT") // actual implementations generated by room
expect object BookDatabaseConstructor: RoomDatabaseConstructor<FavoriteBookDatabase> {
    override fun initialize(): FavoriteBookDatabase
}